### ISSUE TITLE
frontend validation for forms. check for valid email and passwrod format

### ISSUE THREAD

**Issue by xCandyFun** [Goteborgs-guiden/Gotehenburg-guide#182]

**Comment by xCandyFun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [frontend validation for forms. check for valid email and passwrod format](https://trello.com/c/R5Cyrb3h/176-frontend-validation-for-forms-check-for-valid-email-and-passwrod-format)

**Comment by signealfonson** [comment]
Closed with #199
