### ISSUE TITLE
Create frontend logic for abc quiz

### ISSUE THREAD

**Issue by williamDenStore** [Goteborgs-guiden/Gotehenburg-guide#24]

**Comment by Viktormes** [comment]
Very unspecified issue. But I can do it anyways.

**Comment by BobHogvall** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create frontend logic for abc quiz](https://trello.com/c/BmHHAJEX/56-create-frontend-logic-for-abc-quiz)
