### ISSUE TITLE
Create wireframe

### ISSUE THREAD

**Issue by williamDenStore** [Goteborgs-guiden/Gotehenburg-guide#3]
create a wireframe for the front end design

**Comment by BobHogvall** [comment]
![Uploading wireframe-project.drawio.png…]()

**Comment by BobHogvall** [comment]
![wireframe-project drawio](https://github.com/Goteborgs-guiden/Gotehenburg-guide/assets/113605310/9b32dc5d-8ad6-4abb-bdf2-31639ca60aab)

**Comment by BobHogvall** [comment]
Wireframe don
